export const browserCoreExamples = [
  "sani browser status",
  "sani browser start",
  "sani browser stop",
  "sani browser tabs",
  "sani browser open https://example.com",
  "sani browser focus abcd1234",
  "sani browser close abcd1234",
  "sani browser screenshot",
  "sani browser screenshot --full-page",
  "sani browser screenshot --ref 12",
  "sani browser snapshot",
  "sani browser snapshot --format aria --limit 200",
  "sani browser snapshot --efficient",
  "sani browser snapshot --labels",
];

export const browserActionExamples = [
  "sani browser navigate https://example.com",
  "sani browser resize 1280 720",
  "sani browser click 12 --double",
  'sani browser type 23 "hello" --submit',
  "sani browser press Enter",
  "sani browser hover 44",
  "sani browser drag 10 11",
  "sani browser select 9 OptionA OptionB",
  "sani browser upload /tmp/file.pdf",
  'sani browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "sani browser dialog --accept",
  'sani browser wait --text "Done"',
  "sani browser evaluate --fn '(el) => el.textContent' --ref 7",
  "sani browser console --level error",
  "sani browser pdf",
];
