name: SANI
options:
  bundleIdPrefix: ai.sani
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  SANIKit:
    path: ../shared/SANIKit
  Swabble:
    path: ../../Swabble

schemes:
  SANI:
    shared: true
    build:
      targets:
        SANI: all
    test:
      targets:
        - SANITests

targets:
  SANI:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: SANIKit
      - package: SANIKit
        product: SANIChatUI
      - package: SANIKit
        product: SANIProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y5PE65HELJ
        PRODUCT_BUNDLE_IDENTIFIER: ai.sani.ios
        PROVISIONING_PROFILE_SPECIFIER: "ai.sani.ios Development"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: SANI
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "2026.2.3"
        CFBundleVersion: "20260202"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: SANI discovers and connects to your SANI gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _sani-gw._tcp
        NSCameraUsageDescription: SANI can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: SANI uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: SANI can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: SANI needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: SANI uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  SANITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: SANI
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.sani.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SANI.app/SANI"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: SANITests
        CFBundleShortVersionString: "2026.2.3"
        CFBundleVersion: "20260202"
